name: Python
on:
  - push
  - pull_request

jobs:

  wheel-linux-aarch64:
    name: Build Linux wheels (Aarch64)
    runs-on: ubuntu-22.04-arm
    steps:
    - uses: actions/checkout@v4
    - name: Build manylinux wheels
      uses: pypa/cibuildwheel@v2.21.3
      env:
        CIBW_ARCHS: aarch64
        CIBW_BUILD: 'cp*-manylinux_aarch64'
      with:
        output-dir: dist
    - uses: actions/upload-artifact@v4
      with:
        name: wheels-manylinux_aarch64
        path: dist/*

  wheel-linux-x86_64:
    name: Build Linux wheels (x86-64)
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    - name: Build manylinux wheels
      uses: pypa/cibuildwheel@v2.21.3
      env:
        CIBW_ARCHS: x86_64
        CIBW_BUILD: 'cp*-manylinux_x86_64'
      with:
        output-dir: dist
    - uses: actions/upload-artifact@v4
      with:
        name: wheels-manylinux_x86_64
        path: dist/*

  wheel-macos-x86_64:
    name: Build MacOS wheels (x86-64)
    runs-on: macOS-13
    steps:
    - uses: actions/checkout@v4
    - name: Build manylinux wheels
      uses: pypa/cibuildwheel@v2.21.3
      env:
        CIBW_ARCHS: x86_64
        CIBW_BUILD: 'cp*-macosx_x86_64'
      with:
        output-dir: dist
    - uses: actions/upload-artifact@v4
      with:
        name: wheels-macosx_x86_64
        path: dist/*

  wheel-macos-aarch64:
    name: Build MacOS wheels (Aarch64)
    runs-on: macOS-13
    steps:
    - uses: actions/checkout@v4
    - uses: dtolnay/rust-toolchain@stable
    - name: Build manylinux wheels
      uses: pypa/cibuildwheel@v2.21.3
      env:
        CIBW_ARCHS: arm64
        CIBW_BUILD: 'cp*-macosx_arm64'
      with:
        output-dir: dist
    - uses: actions/upload-artifact@v4
      with:
        name: wheels-macosx_arm64
        path: dist/*

  wheel-win32-x86_64:
    name: Build Windows wheels (x86-64)
    runs-on: windows-2019
    steps:
    - uses: actions/checkout@v4
    - uses: dtolnay/rust-toolchain@stable
    - name: Build manylinux wheels
      uses: pypa/cibuildwheel@v2.21.3
      env:
        CIBW_ARCHS: AMD64
        CIBW_BUILD: 'cp*-win_amd64'
      with:
        output-dir: dist
    - uses: actions/upload-artifact@v4
      with:
        name: wheels-win_amd64
        path: dist/*

  sdist:
    runs-on: ubuntu-latest
    name: Build source distribution
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
    - name: Set up Python 3.13
      uses: actions/setup-python@v5
      with:
        python-version: 3.13
    - name: Install CI requirements
      run: python -m pip install -U build maturin
    - name: Build source distribution without vendored sources
      run: python -m build -s . -n
    - uses: actions/upload-artifact@v4
      with:
        name: sdist
        path: dist/*
